excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - trailing_whitespace
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - file_length
