os: osx
osx_image: xcode10.3
language: swift

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

stages:
  - name: lint
  - name: carthage
  - name: test
  - name: deploy

jobs:
  include:

    # - &pod
    #   stage: lint
    #   install: gem install cocoapods -v '~> 1.7.0'
    #   script: pod lib lint --fail-fast --allow-warnings

    # - &carthage
    #   stage: carthage
    #   name: iOS
    #   env: PLATFORM=ios
    #   before_install:
    #   - brew update
    #   - brew outdated carthage || brew upgrade carthage
    #   before_script: |
    #     sed -i '' "s/SWIFT_TREAT_WARNINGS_AS_ERRORS = NO;/SWIFT_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
    #     sed -i '' "s/GCC_TREAT_WARNINGS_AS_ERRORS = NO;/GCC_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
    #   script: carthage build --no-skip-current --configuration Release --platform $PLATFORM
    # - <<: *carthage
    #   name: tvOS
    #   env: PLATFORM=tvos
    # - <<: *carthage
    #   name: macOS
    #   env: PLATFORM=macos

    - &test
      stage: test
      name: iOS
      xcode_scheme: 'YouboraLib iOS'
      xcode_project: YouboraLib.xcodeproj
      xcode_destination: 'platform=iOS Simulator,OS=12.2,name=iPhone SE'
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage update
    - <<: *test
      name: tvOS
      xcode_scheme: 'YouboraLib tvOS'
      xcode_destination: 'platform=tvOS Simulator,OS=12.2,name=Apple TV'
    - <<: *test
      name: tvOS
      xcode_scheme: 'YouboraLib OSX'
      xcode_destination: 'platform=macOS'

