branches:
  only:
  - master

language: objective-c
osx_image: xcode8.3

script:
  # Build lib
  - xcodebuild clean build -scheme YouboraLib\ iOS
  # Build test target fist
  - xcodebuild build -target YouboraLibTest\ iOS
  # Run tests
  - xcodebuild test -scheme YouboraLib\ iOS -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
