branches:
  only:
  - master

language: objective-c
osx_image: xcode10.1

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - carthage update --platform ios,tvos

script:
  # Open simulator
  - open -b com.apple.iphonesimulator
  # Build lib
  - xcodebuild clean build -scheme YouboraLib\ iOS
  # Run tests
  - xcodebuild test -scheme YouboraLib\ iOS -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.1' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  # bash <(curl -s https://codecov.io/bash)
  - ruby scripts/createManifest.rb YouboraLib YouboraLib
  - ruby scripts/make_deployable.rb
  - ruby scripts/deploy_to_qa.rb

after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash

env:
  - QA_KNOWN_HOSTS="qa-smartplugin.youbora.com,81.171.21.12 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM6lBT/mNpS5Sl2GtOiZiWsMr1XB+tluRmakhEyjPtOjQRjbP4Z/D9+yK0Iy5v99pecazEDuigHh5BZ2v3zWYUw="
