//
//  YBOptionsKeysTest.swift
//  YouboraLibTests iOS
//
//  Created by Tiago Pereira on 22/10/2020.
//  Copyright © 2020 NPAW. All rights reserved.
//

import XCTest

class YBOptionsKeysTest: XCTestCase {
    
    func testKeysAndStrings() {
        for property in YBOptionsKeys.Property.allCases {
            switch property {
            case .enabled: XCTAssertEqual(YBOptionsKeys.getProperty(key: "enabled"), property)
            case .httpSecure: XCTAssertEqual(YBOptionsKeys.getProperty(key: "httpSecure"), property)
            case .host:  XCTAssertEqual(YBOptionsKeys.getProperty(key: "host"), property)
            case .accountCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "accountCode"), property)
            case .parseResource: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseResource"), property)
            case .parseHls: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseHls"), property)
            case .parseDash: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseDash"), property)
            case .parseLocationHeader: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseLocationHeader"), property)
            case .parseCdnNameHeader: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseCdnNameHeader"), property)
            case .parseCdnNode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseCdnNode"), property)
            case .parseCdnNodeList: XCTAssertEqual(YBOptionsKeys.getProperty(key: "parseCdnNodeList"), property)
            case .cdnSwitchHeader: XCTAssertEqual(YBOptionsKeys.getProperty(key: "cdnSwitchHeader"), property)
            case .cdnTTL: XCTAssertEqual(YBOptionsKeys.getProperty(key: "cdnTTL"), property)
            case .experimentIds: XCTAssertEqual(YBOptionsKeys.getProperty(key: "experimentIds"), property)
            case .networkIP: XCTAssertEqual(YBOptionsKeys.getProperty(key: "networkIP"), property)
            case .networkIsp: XCTAssertEqual(YBOptionsKeys.getProperty(key: "networkIsp"), property)
            case .networkConnectionType: XCTAssertEqual(YBOptionsKeys.getProperty(key: "networkConnectionType"), property)
            case .forceInit: XCTAssertEqual(YBOptionsKeys.getProperty(key: "forceInit"), property)
            case .sendTotalBytes: XCTAssertEqual(YBOptionsKeys.getProperty(key: "sendTotalBytes"), property)
            case .sessionMetrics: XCTAssertEqual(YBOptionsKeys.getProperty(key: "sessionMetrics"), property)
            case .autoDetectBackground: XCTAssertEqual(YBOptionsKeys.getProperty(key: "autoDetectBackground"), property)
            case .offline: XCTAssertEqual(YBOptionsKeys.getProperty(key: "offline"), property)
            case .isInfinity: XCTAssertEqual(YBOptionsKeys.getProperty(key: "isInfinity"), property)
            case .smartswitchConfigCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "smartswitchConfigCode"), property)
            case .smartswitchGroupCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "smartswitchGroupCode"), property)
            case .smartswitchContractCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "smartswitchContractCode"), property)
            case .appName: XCTAssertEqual(YBOptionsKeys.getProperty(key: "appName"), property)
            case .appReleaseVersion: XCTAssertEqual(YBOptionsKeys.getProperty(key: "appReleaseVersion"), property)
            case .waitForMetadata: XCTAssertEqual(YBOptionsKeys.getProperty(key: "waitForMetadata"), property)
            case .pendingMetadata: XCTAssertEqual(YBOptionsKeys.getProperty(key: "pendingMetadata"), property)
            case .username: XCTAssertEqual(YBOptionsKeys.getProperty(key: "username"), property)
            case .userType: XCTAssertEqual(YBOptionsKeys.getProperty(key: "userType"), property)
            case .userEmail: XCTAssertEqual(YBOptionsKeys.getProperty(key: "userEmail"), property)
            case .networkObfuscateIp: XCTAssertEqual(YBOptionsKeys.getProperty(key: "networkObfuscateIp"), property)
            case .userObfuscateIp: XCTAssertEqual(YBOptionsKeys.getProperty(key: "userObfuscateIp"), property)
            case .anonymousUser: XCTAssertEqual(YBOptionsKeys.getProperty(key: "anonymousUser"), property)
            case .deviceCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceCode"), property)
            case .deviceModel: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceModel"), property)
            case .deviceBrand: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceBrand"), property)
            case .deviceType: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceType"), property)
            case .deviceName: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceName"), property)
            case .deviceOsName: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceOsName"), property)
            case .deviceOsVersion: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceOsVersion"), property)
            case .deviceIsAnonymous: XCTAssertEqual(YBOptionsKeys.getProperty(key: "deviceIsAnonymous"), property)
            case .contentResource: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentResource"), property)
            case .contentIsLive: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentIsLive"), property)
            case .contentTitle: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentTitle"), property)
            case .contentTitle2: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentTitle2"), property)
            case .program: XCTAssertEqual(YBOptionsKeys.getProperty(key: "program"), property)
            case .contentDuration: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentDuration"), property)
            case .contentTransactionCode: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentTransactionCode"), property)
            case .contentBitrate: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentBitrate"), property)
            case .contentStreamingProtocol: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentStreamingProtocol"), property)
            case .contentTransportFormat: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentTransportFormat"), property)
            case .contentThroughput: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentThroughput"), property)
            case .contentRendition: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentRendition"), property)
            case .contentCdn: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCdn"), property)
            case .contentFps: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentFps"), property)
            case .contentMetadata: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentMetadata"), property)
            case .contentMetrics: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentMetrics"), property)
            case .contentIsLiveNoSeek: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentIsLiveNoSeek"), property)
            case .contentPackage: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentPackage"), property)
            case .contentSaga: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentSaga"), property)
            case .contentTvShow: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentTvShow"), property)
            case .contentSeason: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentSeason"), property)
            case .contentEpisodeTitle: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEpisodeTitle"), property)
            case .contentChannel: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentChannel"), property)
            case .contentId: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentId"), property)
            case .contentImdbId: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentImdbId"), property)
            case .contentGracenoteId: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentGracenoteId"), property)
            case .contentType: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentType"), property)
            case .contentGenre: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentGenre"), property)
            case .contentLanguage: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentLanguage"), property)
            case .contentSubtitles: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentSubtitles"), property)
            case .contentContractedResolution: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentContractedResolution"), property)
            case .contentCost: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCost"), property)
            case .contentPrice: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentPrice"), property)
            case .contentPlaybackType: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentPlaybackType"), property)
            case .contentDrm: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentDrm"), property)
            case .contentEncodingVideoCodec: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEncodingVideoCodec"), property)
            case .contentEncodingAudioCodec: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEncodingAudioCodec"), property)
            case .contentEncodingCodecSettings: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEncodingCodecSettings"), property)
            case .contentEncodingCodecProfile: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEncodingCodecProfile"), property)
            case .contentEncodingContainerFormat: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentEncodingContainerFormat"), property)
            case .contentCustomDimension1: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension1"), property)
            case .contentCustomDimension2: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension2"), property)
            case .contentCustomDimension3: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension3"), property)
            case .contentCustomDimension4: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension4"), property)
            case .contentCustomDimension5: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension5"), property)
            case .contentCustomDimension6: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension6"), property)
            case .contentCustomDimension7: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension7"), property)
            case .contentCustomDimension8: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension8"), property)
            case .contentCustomDimension9: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension9"), property)
            case .contentCustomDimension10: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension10"), property)
            case .contentCustomDimension11: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension11"), property)
            case .contentCustomDimension12: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension12"), property)
            case .contentCustomDimension13: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension13"), property)
            case .contentCustomDimension14: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension14"), property)
            case .contentCustomDimension15: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension15"), property)
            case .contentCustomDimension16: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension16"), property)
            case .contentCustomDimension17: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension17"), property)
            case .contentCustomDimension18: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension18"), property)
            case .contentCustomDimension19: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension19"), property)
            case .contentCustomDimension20: XCTAssertEqual(YBOptionsKeys.getProperty(key: "contentCustomDimension20"), property)
            case .customDimension1: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension1"), property)
            case .customDimension2: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension2"), property)
            case .customDimension3: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension3"), property)
            case .customDimension4: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension4"), property)
            case .customDimension5: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension5"), property)
            case .customDimension6: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension6"), property)
            case .customDimension7: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension7"), property)
            case .customDimension8: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension8"), property)
            case .customDimension9: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension9"), property)
            case .customDimension10: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension10"), property)
            case .customDimension11: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension11"), property)
            case .customDimension12: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension12"), property)
            case .customDimension13: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension13"), property)
            case .customDimension14: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension14"), property)
            case .customDimension15: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension15"), property)
            case .customDimension16: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension16"), property)
            case .customDimension17: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension17"), property)
            case .customDimension18: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension18"), property)
            case .customDimension19: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension19"), property)
            case .customDimension20: XCTAssertEqual(YBOptionsKeys.getProperty(key: "customDimension20"), property)
            case .adMetadata: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adMetadata"), property)
            case .adsAfterStop: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adsAfterStop"), property)
            case .adCampaign: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCampaign"), property)
            case .adTitle: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adTitle"), property)
            case .adResource: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adResource"), property)
            case .adGivenBreaks: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adGivenBreaks"), property)
            case .adExpectedBreaks: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExpectedBreaks"), property)
            case .adExpectedPattern: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExpectedPattern"), property)
            case .adBreaksTime: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adBreaksTime"), property)
            case .adGivenAds: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adGivenAds"), property)
            case .adCreativeId: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCreativeId"), property)
            case .adProvider: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adProvider"), property)
            case .adCustomDimension1: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension1"), property)
            case .adCustomDimension2: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension2"), property)
            case .adCustomDimension3: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension3"), property)
            case .adCustomDimension4: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension4"), property)
            case .adCustomDimension5: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension5"), property)
            case .adCustomDimension6: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension6"), property)
            case .adCustomDimension7: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension7"), property)
            case .adCustomDimension8: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension8"), property)
            case .adCustomDimension9: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension9"), property)
            case .adCustomDimension10: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adCustomDimension10"), property)
            case .adExtraparam1: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam1"), property)
            case .adExtraparam2: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam2"), property)
            case .adExtraparam3: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam3"), property)
            case .adExtraparam4: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam4"), property)
            case .adExtraparam5: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam5"), property)
            case .adExtraparam6: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam6"), property)
            case .adExtraparam7: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam7"), property)
            case .adExtraparam8: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam8"), property)
            case .adExtraparam9: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam9"), property)
            case .adExtraparam10: XCTAssertEqual(YBOptionsKeys.getProperty(key: "adExtraparam10"), property)
            }
        }
    }
    
}
